In [ ]:
import numpy as np

# input_m=np.zeros((6,6))
input_m = np.random.randn(6, 6)

# kernel=np.zeros((3,3))
kernel = np.random.randint(0, 10, (3,3))
input_m
kernel


array([[1, 3, 7],
       [4, 9, 6],
       [7, 0, 2]])

In [13]:
print(input_m)

[[-0.05906131 -0.88966727 -1.27743222 -0.04463926  1.55094193  0.87842601]
 [ 0.29005067 -1.11262441 -0.89671449 -1.69721509  0.68963333  0.07291672]
 [ 0.16954301 -0.89061033  0.72336863 -0.99020071 -0.92694028  1.30727226]
 [-2.33457116  0.15996664  0.80622782 -0.72362987  0.66327947 -0.71512842]
 [ 0.17951268 -0.46843286 -0.87285537 -1.05356402  2.29205408  0.82151561]
 [ 1.33050664 -1.2001425   0.16767311 -0.18746377  0.8666633   0.64838883]]


In [19]:
import torch
import torch.nn.functional as F

In [23]:
signal_t = torch.tensor(input_m, dtype=torch.float32)
kernel_t = torch.tensor(kernel, dtype=torch.float32)

signal_uq = signal_t.unsqueeze(0).unsqueeze(0)  # 变成 (1, 1, 3, 3)
kernel_uq = kernel_t.unsqueeze(0).unsqueeze(0)  # 变成 (1, 1, 2, 2)

# 使用 conv2d 进行二维卷积
result = F.conv2d(signal_uq, kernel_uq, padding=0)
print(result)

tensor([[[[-23.2703, -35.9533,  -2.0690,   6.2956],
          [-27.0515, -19.0041,  -5.7707, -10.0732],
          [ -0.9890,  -7.4839,  -9.5698,  -1.5678],
          [  4.7028, -27.3135,   6.9642,  17.5882]]]])


In [30]:
from scipy.signal import convolve2d
input_m_2 = np.random.randint(0, 10, (6,6))
result = convolve2d(input_m_2, kernel, mode='valid')
print(result)
# convolution_result = np.convolve(input_m, kernel, mode='valid ')  # 'full' 返回完整的卷积结果

[[254 175 170 216]
 [230 249 175 242]
 [190 205 132 179]
 [140 185  91 175]]


In [31]:
print(input_m_2)

[[4 9 8 0 2 7]
 [6 7 0 5 3 9]
 [8 9 8 8 3 9]
 [6 5 0 7 1 6]
 [1 9 3 1 4 6]
 [2 4 3 4 8 1]]


In [11]:
print(input_m)
# new_input=input_m[:3]
# print(new_input)
# print(new_input[0])

[[-0.05906131 -0.88966727 -1.27743222 -0.04463926  1.55094193  0.87842601]
 [ 0.29005067 -1.11262441 -0.89671449 -1.69721509  0.68963333  0.07291672]
 [ 0.16954301 -0.89061033  0.72336863 -0.99020071 -0.92694028  1.30727226]
 [-2.33457116  0.15996664  0.80622782 -0.72362987  0.66327947 -0.71512842]
 [ 0.17951268 -0.46843286 -0.87285537 -1.05356402  2.29205408  0.82151561]
 [ 1.33050664 -1.2001425   0.16767311 -0.18746377  0.8666633   0.64838883]]


In [ ]:
new_input=input_m[:3]

In [16]:
size_k=kernel.shape[0]

output_m=[]

for row_ in range(0,len(input_m[0])-size_k+1,1):
    output_row=[]
    for line_ in range(0,len(input_m[:,:1])-size_k+1,1):
        #首先从输入中取和kernel-size一样的行数
        value_row=input_m[row_:row_+size_k]
        #从选出来的行数取和kernel size一样的列数
        value_line=value_row[:,line_:line_+size_k]
        sub_matrix=value_line
        print(sub_matrix)
        
        #计算每一个子矩阵和kernel的乘积,得到输出矩阵的第一行的单个值
        output_row_=0
        for i in range(0,size_k):
            for j in range(0,size_k):
                print(f"{sub_matrix[i][j]} * {kernel[i][j]}")
                output_row_+=sub_matrix[i][j]*kernel[i][j]

        print(output_row_)
        output_row.append(output_row_)
    print(output_row)
    output_m.append(output_row)
print(output_m)


[[-0.05906131 -0.88966727 -1.27743222]
 [ 0.29005067 -1.11262441 -0.89671449]
 [ 0.16954301 -0.89061033  0.72336863]]
-0.05906131320896061 * 1
-0.8896672740544372 * 3
-1.2774322158594196 * 7
0.2900506716863282 * 4
-1.1126244092910287 * 9
-0.8967144937306751 * 6
0.16954301238463684 * 7
-0.8906103267125769 * 0
0.7233686332397269 * 2
-23.270254252474295
[[-0.88966727 -1.27743222 -0.04463926]
 [-1.11262441 -0.89671449 -1.69721509]
 [-0.89061033  0.72336863 -0.99020071]]
-0.8896672740544372 * 1
-1.2774322158594196 * 3
-0.04463925522920486 * 7
-1.1126244092910287 * 4
-0.8967144937306751 * 9
-1.6972150858960646 * 6
-0.8906103267125769 * 7
0.7233686332397269 * 0
-0.9902007114169681 * 2
-35.95333101417568
[[-1.27743222 -0.04463926  1.55094193]
 [-0.89671449 -1.69721509  0.68963333]
 [ 0.72336863 -0.99020071 -0.92694028]]
-1.2774322158594196 * 1
-0.04463925522920486 * 3
1.55094192844962 * 7
-0.8967144937306751 * 4
-1.6972150858960646 * 9
0.6896333330583889 * 6
0.7233686332397269 * 7
-0.990200711